/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.2.1
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CreateIndexSuccessIndexes {
    result: CreateIndexSuccessIndexes.ResultEnum;
}
export namespace CreateIndexSuccessIndexes {
    export type ResultEnum = 'created';
    export const ResultEnum = {
        Created: 'created' as ResultEnum
    }
}
