/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DeleteIndexSuccessIndex {
    result: DeleteIndexSuccessIndex.ResultEnum;
}
export namespace DeleteIndexSuccessIndex {
    export type ResultEnum = 'deleted';
    export const ResultEnum = {
        Deleted: 'deleted' as ResultEnum
    }
}
