/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InlineResponse2001Index {
    result: InlineResponse2001Index.ResultEnum;
}
export namespace InlineResponse2001Index {
    export type ResultEnum = 'available';
    export const ResultEnum = {
        Available: 'available' as ResultEnum
    }
}
