/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.2.1
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SearchQuerySearchAggregations {
    fieldName: string;
    aggType: SearchQuerySearchAggregations.AggTypeEnum;
    termAggSize?: number;
    range?: Array<any>;
    origin?: Array<any>;
    buckets?: number;
}
export namespace SearchQuerySearchAggregations {
    export type AggTypeEnum = 'term' | 'range' | 'histogram' | 'location';
    export const AggTypeEnum = {
        Term: 'term' as AggTypeEnum,
        Range: 'range' as AggTypeEnum,
        Histogram: 'histogram' as AggTypeEnum,
        Location: 'location' as AggTypeEnum
    }
}
