/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.3.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SuggestFailureSuggestResultsMetadata } from './suggestFailureSuggestResultsMetadata';


export interface SuggestFailureSuggestResults {
    error: string;
    metadata: SuggestFailureSuggestResultsMetadata;
}
